name: light
description: Light novel reader.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  path_provider: any
  file: ^2.3.7
  html: any
  flutter_webview_plugin: ^0.1.3
  url_launcher: ^3.0.0
  sqflite: ^0.8.4
  shared_preferences: ^0.4.0
  options_file: any
  crypto: "^2.0.2+1"
  epub:
    git: https://github.com/creatint/dart-epub-cn
  html2md: ^0.1.7
#    path: d:/tmp/html2md/
#  mimic:
#    path: d:/tmp/mimic/

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/light.db
   - assets/config.ini
   - assets/default_cover.jpg
   - assets/background/bg1.png
   - assets/background/bg2.png
   - assets/background/bg3.png
   - assets/background/bg4.png
   - assets/background/bg5.png
   - assets/background/bg6.png
   - assets/background/bg7.jpg
   - assets/background/bg8.png
   - assets/background/bg9.png
   - assets/background/bg10.png
   - assets/background/bg11.png

  fonts:
   - family: Lora
     fonts:
       - asset: assets/font/Lora-Regular.ttf
   - family: HYQH
     fonts:
       - asset: assets/font/HYQH.ttf
   - family: FZYouH
     fonts:
       - asset: assets/font/FZYouH.ttf
   - family: Avenir
     fonts:
       - asset: assets/font/Avenir.ttf
   - family: Noto
     fonts:
       - asset: assets/font/Noto Serif.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
